### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by GeraldN74** [MicroTekAppDev/Attune.Website.Issues#182]
Testimonials for Meeting spaces reference customer training quotes Should be Meeting spaces quotes

**Comment by aj-mclabs** [comment]
@GeraldN74 can you please provide the link for the page you're seeing this on?

**Comment by GeraldN74** [comment]
https://test-umb.attune.com/spaces/

Quotes under Recent Feedback


Gerald Neri
VP of Sales and Marketing
MicroTek - www.mclabs.com<http://www.mclabs.com/>
P:  610 337 3811 x 450
C: 609 317 5209
E:  gerald.neri@mclabs.com

**Comment by connorsli** [comment]
We are in the process of splitting our testimonial bank into 3 (general, meeting and training) so that we can have it pull one at a time or both types if needed.  

The problem so far is our quotes are mostly training focused and our "meeting" side is pretty light.
AJ and I will get together with Angel and Beth to see the best way to source/collect some more.

**Comment by aj-mclabs** [comment]
@GeraldN74 The Spaces (location search) page you linked is agnostic, so it is currently pulling in both meeting and training quotes at random. There may be a higher proportion of training quotes currently, but that will balance out as we get more meeting clients.
